# ============================================================
# Retail Growth — Final project audit
#
# Purpose:
# Verify that the major platform components created across
# the project are present and internally consistent.
#
# This is NOT a replacement for:
#
# - unit tests
# - dbt tests
# - Airflow execution
# - GitHub Actions
#
# Instead, it provides a final structural inventory.
# ============================================================

from pathlib import Path
import json
import sys

import joblib


PROJECT_ROOT = (
    Path(__file__).resolve().parents[1]
)

sys.path.insert(
    0,
    str(PROJECT_ROOT),
)


from src.governance import (
    sha256_file,
)


# ------------------------------------------------------------
# 1. Expected project components
# ------------------------------------------------------------

REQUIRED_PATHS = {

    "dbt project":
        "dbt/dbt_project.yml",

    "Airflow DAG":
        "orchestration/dags/retail_growth_refresh.py",

    "decision engine":
        "src/decisioning.py",

    "drift monitoring":
        "src/drift_monitoring.py",

    "governance utilities":
        "src/governance.py",

    "FastAPI application":
        "api/app.py",

    "API Dockerfile":
        "api/Dockerfile",

    "CI workflow":
        ".github/workflows/ci.yml",

    "incremental ingestion generator":
        "scripts/generate_incremental_demo.py",

    "Kafka producer":
        "streaming/produce_events.py",

    "Spark streaming pipeline":
        "streaming/spark_pipeline.py",

    "model card":
        "docs/model_card.md",

    "system architecture":
        "docs/system_architecture.md",
}


# ------------------------------------------------------------
# 2. Verify repository components
# ------------------------------------------------------------

def audit_required_paths():

    rows = []

    for component, relative_path in (
        REQUIRED_PATHS.items()
    ):

        path = (
            PROJECT_ROOT
            / relative_path
        )

        rows.append(
            {
                "component":
                    component,

                "path":
                    relative_path,

                "exists":
                    path.exists(),
            }
        )

    missing = [
        row
        for row in rows
        if not row["exists"]
    ]

    if missing:

        formatted = "\n".join(
            f"- {row['component']}: "
            f"{row['path']}"
            for row in missing
        )

        raise RuntimeError(
            "Required project components "
            "are missing:\n"
            f"{formatted}"
        )

    return rows


# ------------------------------------------------------------
# 3. Verify model artifact
# ------------------------------------------------------------

def audit_model():

    model_path = (
        PROJECT_ROOT
        / "data"
        / "models"
        / "logistic_t_learner_full.joblib"
    )

    if not model_path.exists():

        raise FileNotFoundError(
            "Trusted model artifact "
            "was not found."
        )

    # Only load the trusted artifact generated by this
    # project.
    model_bundle = joblib.load(
        model_path
    )

    feature_columns = list(
        model_bundle[
            "feature_columns"
        ]
    )

    return {

        "model_family":
            model_bundle.get(
                "model_family"
            ),

        "feature_count":
            len(
                feature_columns
            ),

        "feature_cutoff":
            str(
                model_bundle.get(
                    "feature_cutoff"
                )
            ),

        "sha256":
            sha256_file(
                model_path
            ),
    }


# ------------------------------------------------------------
# 4. Verify dbt manifest
# ------------------------------------------------------------

def audit_dbt():

    manifest_path = (
        PROJECT_ROOT
        / "dbt"
        / "target"
        / "manifest.json"
    )

    if not manifest_path.exists():

        raise FileNotFoundError(
            "dbt manifest.json was not found."
        )

    manifest = json.loads(
        manifest_path.read_text(
            encoding="utf-8"
        )
    )

    target_models = {
        "mart_customer_features",
        "mart_uplift_training",
        "mart_uplift_scoring",
    }

    discovered_models = {
        node.get("name")
        for node in (
            manifest
            .get(
                "nodes",
                {}
            )
            .values()
        )
        if (
            node.get(
                "resource_type"
            )
            == "model"
        )
    }

    missing_models = (
        target_models
        - discovered_models
    )

    if missing_models:

        raise RuntimeError(
            "Required dbt models missing: "
            f"{sorted(missing_models)}"
        )

    return {
        "required_models_verified":
            len(target_models),
    }


# ------------------------------------------------------------
# 5. Run final audit
# ------------------------------------------------------------

def main():

    components = (
        audit_required_paths()
    )

    model = audit_model()

    dbt = audit_dbt()

    print(
        "\nRetail Growth Platform Audit\n"
    )

    for component in components:

        print(
            "PASS:",
            component[
                "component"
            ],
        )

    print(
        "\nModel:"
    )

    print(
        "  family:",
        model[
            "model_family"
        ],
    )

    print(
        "  features:",
        model[
            "feature_count"
        ],
    )

    print(
        "  feature cutoff:",
        model[
            "feature_cutoff"
        ],
    )

    print(
        "  SHA-256:",
        model[
            "sha256"
        ],
    )

    print(
        "\ndbt:"
    )

    print(
        "  required marts verified:",
        dbt[
            "required_models_verified"
        ],
    )

    print(
        "\nPASS: Final platform audit completed."
    )


if __name__ == "__main__":
    main()